# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Bash.gitlab-ci.yml

# See https://docs.gitlab.com/ee/ci/yaml/index.html for all available options

# you can delete this line if you're not using Docker
#image: busybox:latest

stages:
  - test
  - dast
  - fuzz
  - build

page_build:
  stage: build
  before_script:
    - yarn install --frozen-lockfile
  script:
    - env CI=true NODE_ENV=production yarn run build
    - mv ./public/404/index.html ./public/404.html
    - rm -rf ./public/404
#  after_script:
#    - rm -rf /home/runner/work/seyoon20087.github.io
#    - git init /home/runner/work/seyoon20087.github.io/seyoon20087.github.io &> /dev/null
#  rules:
#    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

include:
  - template: Security/SAST.gitlab-ci.yml
#  - template: DAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
#  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
#  - template: API-Fuzzing.gitlab-ci.yml
  - template: Security/Cluster-Image-Scanning.gitlab-ci.yml